python run.py \
    --test_file data/run.jsonl \
    --headless \
    --max_iter 15 \
    --max_attached_imgs 3 \
    --temperature 1 \
    --fix_box_color \
    --seed 42 \
    --web_markdown \
    --web_assistant \
    --dynamic_load \
    --web_observer \
    --api_key OPENAI_API_KEY \
    --api_model gpt-4o